---
:options:
  :minimum_activation_time: 10
:files:
  :inbox: data/inbox.yaml
  :random_phrases: data/random_phrases.yaml
:twitter:
  :consumer_key: 
  :consumer_secret: 
  :access_token: 
  :access_token_secret: 
